45744 Maritime Safety Information - FSS DotNet Client - Add method for GetFilesAsZip endpoint
UKHO/file-share-dotnet-client pull request #34
Opened 2022-05-26 11:13 UTC by usha13529

Hi All, please review and merge changes related to PBI:45744 - Task:48544 - To add method for GetFilesAsZip endpoint to be used for download daily notices to mariners zip file in Maritime Safety Information.

2022-05-27 06:08 UTC, vijendr13545 approved these changes
Looks good to me, thanks.

2022-05-27 08:23 UTC, crdandoukho requested changes

2022-05-27 08:23 UTC, crdandoukho commented on FileShareClient/FileShareApiClient.cs
> +        public async Task<Stream> DownloadZipFileAsync(string batchId, CancellationToken cancellationToken)
Please change `DownloadZipFileAsync` to return `Task<IResult<Stream>>`

The IResult interface is intended to return additional error information to callers without the callers having to couple themselves to the format/content/type of exceptions returned by the API

2022-05-30 08:42 UTC, crdandoukho approved these changes

2022-05-30 08:43 UTC, merged